### ISSUE TITLE
Minor issues - Bad indentation and prefix name.

### ISSUE THREAD

**Issue by andrewCluey** [dvonessen/aws-cloudformation-yaml#1] opened 2017-10-16 22:10 UTC
Some of the snippets return bad indentation in YAML format. Example 'Customer' & 'CustomerProject' in AWSTemplate are at different levels.

Also, seems to be an issue with some Snippets and intellisense. Changing the AWSTemplate prefix (for example) to '!AWSTemplate" resolved this for me (I'm running Mac version of VS Code BTW. 

Seems odd as the snippet for creating a new resource ("prefix": 'NewResource') works fine without any modification.

**Comment by bitfoo1** [comment] 2017-10-17 11:44
Hi thank you for using my extension. I will try my best to fix all mentioned bugs.

Which version of my extension are you using?
And which version of VS Code?

**Comment by bitfoo1** [comment] 2017-10-17 13:25
I released a new version of this extension. Unfortunately i do not understand your issue with the Snippets and Intellisense. Maybe you can give me further information.

New Version is now 0.1.0 and available on the marketplace.

**Comment by andrewCluey** [comment] 2017-10-17 13:59
Hi Daniel, it's only a minor issue I'm seeing and the workaround I'm using works fine for me. This may be something I'm seeing in my environments (or user error :-) ). 

If you want to see if you can re-create though I'll try and be a bit more specific. First off, I've seen this issue on two separate installations of VS Code (1 of which is MAC Installation). the other is v 1.17.1 on Windows 2012 Server R2.

So, when I try to use the "AWS Cloud Formation Template" snippet (by using the prefix AWSTemplate, Intellisense doesn't return anything for me to select in my yaml file. Other snippets (such as NewResource, for example, get returned by Intellisense without any issues as soon as I start typing 'N' or '!' (for example).

This issue is also evident on some other of the snippets, for example 'Parameter' and 'Output'. 

However, if I edit the Yaml.json file and add a '!' to the prefix of each snippet that isn't working, they work perfectly. Seems really odd that it would work by adding a '!' to the prefix, really don't see why that would make a difference, so maybe I'm missing something obvious.

Some images to help explain what I'm seeing. 

1. Image of the Yaml.json file before any changes (just the AWS Cloud Formation template section).

![image](https://user-images.githubusercontent.com/13432888/31668189-63cfea9c-b349-11e7-88e4-adece5cc4885.png)

2. Image of editing a YAML file, attempting to add the AWSTemplate Snippet using the prefix 'AWS'.

![image](https://user-images.githubusercontent.com/13432888/31668234-82ec984e-b349-11e7-8267-97515d2f27cf.png)

3. Image showing how the other snippets in the extension work.

![image](https://user-images.githubusercontent.com/13432888/31668250-946a913e-b349-11e7-827e-d3de1a84335a.png)

4. Image showing the change made to the yaml.json file.

![image](https://user-images.githubusercontent.com/13432888/31668267-a2b548a6-b349-11e7-8ce7-7b1168012320.png)

5. Image showing the AWSTemplate snippet being available in the yaml file I'm working on after adding the '!' to the prefix. 

![image](https://user-images.githubusercontent.com/13432888/31668301-bdd2e13e-b349-11e7-9f0d-13adbe8e6e23.png)

**Comment by bitfoo1** [comment] 2017-10-18 06:28
@andrewCluey I hope you received the updated version of my extension v0.1.0 unfortunatley I do not own a Mac, so I cannot reproduce your error. On my VS Code V1.17.1 everything works fine. 

I would try something else. To get a clean profile please follow the instructions.
1.  Download the insider version of vs code
1.1 [vscode insider](https://code.visualstudio.com/insiders/). 
2. Install and start vscode insider
3. Install **only** my extension 
4. Try to use the extensions snippet for "AWS  Cloud Formation Template"

If you followed these steps please let me know if everything is working or not. If not I will try to find someone who has a Mac to reproduce your error or I will start a installation of vscode on Windows Server 2012 R2.

Hope we will find whats wrong so that your experience with my extension will getting better.

Best regards Daniel

**Comment by andrewCluey** [comment] 2017-10-24 10:24
Thanks Daniel, I'll try the installation of VScode insider. Just for info, I'm getting the same issues with my installation of VSCode on my Windows 10 system too. All the snippets starting with a '!' work fine, the others don't (Unless I edit the YAML.JSON snippet file to add a '!' to all prefixes).

**Comment by bitfoo1** [comment] 2017-10-24 11:36
Sure but I already tested it on Windows 10 and Mac. And I cannot see any issues. 
So maybe there is something wrong with your configured vs code environment.
Therefore I recommended already to use the inside build, because this uses a complete clean environment.

**Comment by daftping** [comment] 2018-01-03 11:33
Hi guys, I have same issue. Only snippets starting with a '!' work fine. Have you managed to fix it?
My env: 
Win10x64 1709
Visual Studio Code
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by daftping** [comment] 2018-01-03 11:46
I've found workaround. Add "editor.quickSuggestions": true to user settings for YAML.
![image](https://user-images.githubusercontent.com/21245083/34519390-682ef134-f08c-11e7-9a8e-86fc13ed509a.png)

**Comment by bitfoo1** [comment] 2018-07-27 06:59
I will close this Issue.
That is not an issue anymore.

**Closed as completed by bitfoo1** 2018-07-27 06:59 UTC
